import { lstat, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import { basename, dirname, join } from 'node:path'
import type { Network } from './config.js'
import { PublishError } from './errors.js'

const HEADER = `# Generated by Move
# This file contains metadata about published versions of this package in different environments
# This file SHOULD be committed to source control
`

function compilerVersion(suiCliVersion: string): string {
  return suiCliVersion.match(/\b(\d+\.\d+\.\d+)/)?.[1] ?? suiCliVersion.replace(/^sui\s+/, '')
}

function moveEdition(manifest: string): string {
  return manifest.match(/^\s*edition\s*=\s*["']([^"']+)["']/m)?.[1] ?? '2024'
}

function publicationSection(options: {
  network: Network
  chainId: string
  packageId: string
  suiCliVersion: string
  edition: string
}): string {
  return `[published.${options.network}]
chain-id = ${JSON.stringify(options.chainId)}
published-at = ${JSON.stringify(options.packageId)}
original-id = ${JSON.stringify(options.packageId)}
version = 1
toolchain-version = ${JSON.stringify(compilerVersion(options.suiCliVersion))}
build-config = { flavor = "sui", edition = ${JSON.stringify(options.edition)} }
`
}

function oneTrailingNewline(value: string): string {
  return `${value.trimEnd()}\n`
}

export function updatePublishedText(
  existing: string,
  options: {
    network: Network
    chainId: string
    packageId: string
    suiCliVersion: string
    edition: string
  },
): string {
  const replacement = publicationSection(options)
  const sectionPattern = new RegExp(`^\\[published\\.${options.network}\\]\\s*$`, 'm')
  const match = sectionPattern.exec(existing)
  if (!match) {
    const prefix = existing.trim() ? `${existing.trimEnd()}\n\n` : `${HEADER}\n`
    return oneTrailingNewline(`${prefix}${replacement}`)
  }

  const start = match.index
  const afterHeader = start + match[0].length
  const nextHeader = /^\[[^\]]+\]\s*$/m.exec(existing.slice(afterHeader))
  const end = nextHeader ? afterHeader + nextHeader.index : existing.length
  const before = existing.slice(0, start)
  const after = existing.slice(end).replace(/^\s*/, '\n\n')
  return oneTrailingNewline(`${before}${replacement.trimEnd()}${after || '\n'}`)
}

export async function updatePublishedFile(options: {
  packagePath: string
  network: Network
  chainId: string
  packageId: string
  suiCliVersion: string
}): Promise<string> {
  const publishedPath = join(options.packagePath, 'Published.toml')
  const manifestPath = join(options.packagePath, 'Move.toml')
  let existing = ''
  try {
    const stat = await lstat(publishedPath)
    if (stat.isSymbolicLink()) {
      throw new PublishError('PUBLISHED_FILE_SYMLINK', 'Refusing to replace a symlinked Published.toml.')
    }
    existing = await readFile(publishedPath, 'utf8')
  } catch (error) {
    if (!(error instanceof PublishError) && (error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    if (error instanceof PublishError) throw error
  }
  const manifest = await readFile(manifestPath, 'utf8')
  const updated = updatePublishedText(existing, {
    network: options.network,
    chainId: options.chainId,
    packageId: options.packageId,
    suiCliVersion: options.suiCliVersion,
    edition: moveEdition(manifest),
  })

  const temporaryPath = join(
    dirname(publishedPath),
    `.${basename(publishedPath)}.${process.pid}.${Date.now()}.tmp`,
  )
  try {
    await writeFile(temporaryPath, updated, { encoding: 'utf8', mode: 0o644, flag: 'wx' })
    await rename(temporaryPath, publishedPath)
  } catch (error) {
    await unlink(temporaryPath).catch(() => undefined)
    throw error
  }
  return publishedPath
}
